### PR TITLE
Add -verbose- option to configuration to enable verbose logging

### PR DESCRIPTION
**Pull request by ridiculous**
Found this to be invaluable when working with mention API

### Changes
* New config option `NameDrop.configuration.verbose` to include the `@detail` in error messages
* Make `Alert#new_record?` public
* Add `Alert#persisted?` to compliment `new_record?`

### Open Questions
* Should this be the default setting?

### CODE REVIEW

**Comment by djreyes** [comment]
LGTM. It sounds like being verbose by default would be useful so I'd be in favor of it.

**Comment by ridiculous** [comment]
Thanks. Yeah, it's just that it could include an entire HTML page or large JSON payloads

**Comment by adambedford** [comment]
I think you should opt-in to verbosity, especially if it could be a large amount of data.

**Comment by ridiculous** [comment]
Yeah, that's what I'm thinking too

**Comment by djreyes** [comment]
Sounds good to me!

**Review by adambedford — APPROVED** [review]

**Pull request merged**
